# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'VishalDemoProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VishalDemoProject
  pod 'IQKeyboardManagerSwift', '~> 8.0'
  # Pods for LiveActivity Generate TOKEN
  pod 'SwiftJWT', '~> 3.5.0'
  
  # Pods for Jitsi meet
  pod 'JitsiMeetSDK', '~> 9.2'
  
  # Pods for Google Ads
  pod 'Google-Mobile-Ads-SDK', '~> 12.8'
  
end
post_install do |installer|
  xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
#      config.build_settings['ENABLE_BITCODE'] = 'NO'
#      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.1'
      # For xcode 15+ only
      if config.base_configuration_reference && Integer(xcode_base_version) >= 15
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
  end
end
