# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WidgetDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WidgetDemo
  pod 'Firebase'#, '~> 8.8'
  pod 'FirebaseCore'#, '~> 8.8'
  pod 'FirebaseMessaging'#, '~> 8.8'
  pod 'FirebaseDynamicLinks'#, '~> 8.8'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'

  pod 'SwiftJWT', '~> 3.5.0'
  
  pod 'Alamofire', '~> 5.7'
end

target 'WidgetExExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WidgetExExtension

end
